### ISSUE TITLE
Show pairwise statistics in matrix form

### ISSUE THREAD

**Issue by anpefi** [elcortegano/metapop2#17]
The output of pairwise parameters between two subpopulations are given in a sequential list. It should be the option to give them as a matrix

**Comment by CORTEGANO** [comment]
This feature has been implemented only for the main output file. I just realized that it may be also convenient for the migration output file generated in the simulation mode, so the issue remains open.

**Comment by CORTEGANO** [comment]
The migration table can also be printed in a pairwise form now.

All simulation output files are now tab-separated.
