### ISSUE TITLE
Test calculations of allelic diversity when dealing with haploid data

### ISSUE THREAD

**Issue by anpefi** [elcortegano/metapop2#23]
Related to #8

**Comment by CORTEGANO** [comment]
Allelic diversity parameters have been revised for haploid data. Everyting seems allright. The program only shows problems when trying to apply management methods to this kind of data.

As it is unlikely that we need haploid data for management, and its difficult to handle these genomes in the management functions (the inheritance does not work the same for the X chromosome, mitochondria or haploid organisms), the use of haploid information is restricted to the population analysis.
