### ISSUE TITLE
Allow coancestry matrix as input

### ISSUE THREAD

**Issue by anpefi** [elcortegano/metapop2#3]
Like in the old java version

**Comment by CORTEGANO** [comment]
An optional genealogical coancestry can now be included in the input data file. When doing so, any analysis will use the information given by this matrix, and not the molecular markers.

This matrix can also be generated in the "Input for the next Generation" section using an option in the `nextgen` parameter of the configuration file. This will be done by default always when using the matrix in the output (also for the simulation mode, though in this case the matrix won't appear in the output file).
