### ISSUE TITLE
Re-activate the option for calculations from Petit (contrib)

### ISSUE THREAD

**Issue by anpefi** [elcortegano/metapop2#6]
In a former version there was an option to emulate the calculations made by contrib (petit et al 1998) but it was disabled. It could be usefulr to have it enalbled again as potional output.

**Comment by anpefi** [comment]
The function calculationsPetit() is yielding a segmentation fault

**Comment by elcortegano** [comment]
It has been decided to deprecate this option, as it is equivalent to the current method to estimate the contributions of each subpopulation to genetic diversity when removing one of them.
